"""
Application constants
"""

# Energy Sources
ENERGY_SOURCE_GRID = "grid"
ENERGY_SOURCE_SOLAR = "solar"
ENERGY_SOURCE_DIESEL = "diesel"

ENERGY_SOURCES = [ENERGY_SOURCE_GRID, ENERGY_SOURCE_SOLAR, ENERGY_SOURCE_DIESEL]

# Time Units
TIME_UNIT_HOURLY = "hourly"
TIME_UNIT_DAILY = "daily"
TIME_UNIT_WEEKLY = "weekly"
TIME_UNIT_MONTHLY = "monthly"

TIME_UNITS = [TIME_UNIT_HOURLY, TIME_UNIT_DAILY, TIME_UNIT_WEEKLY, TIME_UNIT_MONTHLY]

# Data Retention (days)
DATA_RETENTION_DAYS_DEFAULT = 90
DATA_RETENTION_DAYS_HISTORICAL = 365

# Pagination
DEFAULT_PAGE_SIZE = 100
MAX_PAGE_SIZE = 1000

# Cache
CACHE_TTL_SECONDS_DEFAULT = 300  # 5 minutes
CACHE_TTL_SECONDS_LONG = 3600  # 1 hour

# Scheduler
SCHEDULER_INGESTION_DEFAULT_TIME = "09:00"
SCHEDULER_EMAIL_DEFAULT_TIME = "18:00"

# Email
EMAIL_REPORT_SUBJECT = "Energy Dashboard Daily Report"
EMAIL_RETRY_ATTEMPTS = 3
EMAIL_RETRY_DELAY_SECONDS = 60

# API
API_TITLE = "Energy Dashboard API"
API_VERSION = "1.0.0"
API_DESCRIPTION = "API for Energy Consumption Monitoring and Analysis - Noida Campus"

# CORS
CORS_ALLOW_METHODS = ["*"]
CORS_ALLOW_HEADERS = ["*"]
CORS_ALLOW_CREDENTIALS = True
